# validate script syntax with http://lint.travis-ci.org/
# base of this file: http://datadesk.latimes.com/posts/2012/06/test-your-django-app-with-travisci/
branches:
  only:
    - master
    - feat/backups_testing
# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "2.7.6"
sudo: required
services: 
  postgresql
addons:
  postgresql: "9.3"
# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.10.3
# Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!
git:
  submodules: false
# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
# Tell it the things it will need to install when it boots
install: 
  # Install the dependencies the app itself 
  - sudo pip install -r requirements.txt 
  # Install whatever version of Django that's listed above
  # Travis is currently working on
  - sudo pip install -q Django==$DJANGO_VERSION 

before_script:
  - sudo psql -c "CREATE DATABASE ghostinspector;" -U postgres
  - sudo psql -c "CREATE USER inspector WITH PASSWORD '1ghost2inspector';" -U postgres
  - sudo psql -c "ALTER USER inspector CREATEDB;" -U postgres
  - sudo psql -c "GRANT ALL PRIVILEGES ON DATABASE ghostinspector TO inspector;" -U postgres
  - sudo cp $TRAVIS_BUILD_DIR/.travis/DTPMConnectionParams.json $TRAVIS_BUILD_DIR/PredictorDTPM/webService/
  - sudo cp $TRAVIS_BUILD_DIR/.travis/secret_key.txt $TRAVIS_BUILD_DIR/server/keys/  
  - sudo cp $TRAVIS_BUILD_DIR/.travis/google_key.json $TRAVIS_BUILD_DIR/server/keys/
  - sudo cp $TRAVIS_BUILD_DIR/.travis/admins.json $TRAVIS_BUILD_DIR/server/keys/
  - sudo cp $TRAVIS_BUILD_DIR/.travis/email_config.json $TRAVIS_BUILD_DIR/server/keys/
  - sudo cp $TRAVIS_BUILD_DIR/.travis/android_requests_backups.py $TRAVIS_BUILD_DIR/server/keys/
  - sudo sed -i 's/<REPLACE_USER>/$USER/' $TRAVIS_BUILD_DIR/server/keys/android_requests_backups.py
  - sudo sed -i 's/<REPLACE_HOME>/$HOME/' $TRAVIS_BUILD_DIR/server/keys/android_requests_backups.py
  - sudo mkdir $TRAVIS_BUILD_DIR/server/logs
  
  ## ssh stuff
  # generate key add to authorized keys and known hosts 
  - "sudo ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -N \"\""
  - "sudo cat $HOME/.ssh/id_rsa.pub >> $HOME/.ssh/authorized_keys"
  - "sudo ssh-keyscan -H localhost  >> $HOME/.ssh/known_hosts"
  # prevent first usage ask for fingerprint
  #- "sudo echo \"Host localhost\"                > $HOME/.ssh/config"
  #- "sudo echo \"    StrictHostKeyChecking no\" >> $HOME/.ssh/config"
  #- "sudo chmod 400 $HOME/.ssh/config"

# Tell Travis how to run the test script itself
script: 
  - "sudo python manage.py test -k AndroidRequestsBackups"
  # - "python manage.py makemigrations"
  # - "python manage.py migrate"
  # - "coverage run --source='.' manage.py test"
  # - "coverage report --omit=DataDictionary/*,server/* -m"

after_success:
  - coveralls
