# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(db_column='patente', max_length=7)),
                ('authRouteCode', models.CharField(db_column='servicio', max_length=50)),
                ('userRouteCode', models.CharField(db_column='servicio_usuario', max_length=50)),
                ('timestamp', models.DateTimeField(db_column='tiempo')),
                ('longitude', models.FloatField(db_column='longitud')),
                ('latitude', models.FloatField(db_column='latitud')),
                ('xUTM', models.IntegerField(db_column='x')),
                ('yUTM', models.IntegerField(db_column='y')),
                ('distanceOnPath', models.IntegerField(db_column='dist_en_ruta')),
                ('distanceToPath', models.IntegerField(db_column='dist_a_ruta')),
                ('speed', models.IntegerField(db_column='velocidad')),
                ('speedWith2GPS', models.IntegerField(db_column='velocidad_2gps')),
                ('speedWith4GPS', models.IntegerField(db_column='velocidad_4gps')),
                ('operator', models.IntegerField(db_column='operador')),
                ('orientation', models.IntegerField(db_column='orientacion')),
                ('orientationAngle', models.IntegerField(db_column='orientacion_angulo')),
                ('type', models.CharField(db_column='tipo', max_length=10)),
                ('busCapacity', models.IntegerField(db_column='capacidad')),
            ],
        ),
    ]
