# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastgps',
            name='detention',
            field=models.IntegerField(db_column='detencion', default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastgps',
            name='timeToPreviousBus',
            field=models.IntegerField(db_column='tiempo_sgt_bus', default=None),
            preserve_default=False,
        ),
    ]
