# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegps', '0002_auto_20170831_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastgps',
            name='authRouteCode',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='busCapacity',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='detention',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='distanceOnPath',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='distanceToPath',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='orientationAngle',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='speedWith2GPS',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='speedWith4GPS',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='timeToPreviousBus',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='xUTM',
        ),
        migrations.RemoveField(
            model_name='lastgps',
            name='yUTM',
        ),
    ]
