# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegps', '0003_auto_20171026_1647'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lastgps',
            index=models.Index(fields=['licensePlate'], name='onlinegps_l_patente_4cefa2_idx'),
        ),
    ]
