# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegps', '0004_auto_20171026_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastGPS',
        ),
    ]
