# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlinegps', '0005_delete_lastgps'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(db_column='patente', max_length=7)),
                ('userRouteCode', models.CharField(db_column='servicio_usuario', max_length=50)),
                ('timestamp', models.DateTimeField(db_column='tiempo')),
                ('latitude', models.FloatField(db_column='latitud')),
                ('longitude', models.FloatField(db_column='longitud')),
            ],
        ),
        migrations.AddIndex(
            model_name='lastgps',
            index=models.Index(fields=['licensePlate'], name='onlinegps_l_patente_4cefa2_idx'),
        ),
    ]
