# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictorDTPM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buslog',
            old_name='serviceName',
            new_name='route',
        ),
        migrations.RemoveField(
            model_name='buslog',
            name='valid',
        ),
        migrations.AddField(
            model_name='buslog',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
