# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictorDTPM', '0002_auto_20170925_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslog',
            name='licensePlate',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
    ]
