# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictorDTPM', '0005_auto_20171010_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslog',
            name='timeMessage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
