# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0034_token_transappuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorehistory',
            name='meta',
            field=models.TextField(null=True),
        ),
    ]
