# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0036_transappuser_externalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transappuser',
            name='externalId',
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False),
        ),
    ]
