# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0037_auto_20171002_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='transappuser',
            name='globalPosition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
