# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0038_transappuser_globalposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transappuser',
            name='globalPosition',
            field=models.BigIntegerField(),
        ),
    ]
