# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0040_fixed_timecreation_20171024_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='transappuser',
            name='timeCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
