# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0042_fixed_timecreation_20171115_1319'),
    ]

    operations = [
        migrations.AlterModelTable(name='BusStop', table='gtfs_busstop'),
        migrations.AlterModelTable(name='GTFS', table='gtfs_gtfs'),
        migrations.AlterModelTable(name='Route', table='gtfs_route'),
        migrations.AlterModelTable(name='Service', table='gtfs_service'),
        migrations.AlterModelTable(name='ServiceLocation', table='gtfs_servicelocation'),
        migrations.AlterModelTable(name='ServicesByBusStop', table='gtfs_servicesbybusstop'),
        migrations.AlterModelTable(name='ServiceStopDistance', table='gtfs_servicestopdistance'),
    ]
