# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0044_auto_20171117_1612'),
    ]

    state_operations = [
        migrations.DeleteModel("BusStop"),
        migrations.DeleteModel("GTFS"),
        migrations.DeleteModel("Route"),
        migrations.DeleteModel("Service"),
        migrations.DeleteModel("ServiceLocation"),
        migrations.DeleteModel("ServicesByBusStop"),
        migrations.DeleteModel("ServiceStopDistance")
    ]

    operations = [
       migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
