# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0049_auto_20171123_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tranSappUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.TranSappUser'),
        ),
    ]
